#!/usr/bin/env bash
# A bash script that lists subdomains

all_subs () {
    dig "$2"."$1" | awk '/ANSWER SECTION/ {getline; print "The subdomain '"$2"' is a A record and points to " $5}'
}

if [ $# -lt 2 ]
then
    all_subs "$1" "www"
    all_subs "$1" "lb-01"
    all_subs "$1" "web-01"
    all_subs "$1" "web-02"
elif [ $# == 2 ]
then
    sd=$2
    all_subs "$1" "$sd"
elif [ $# == 0 ]
then
    echo "Usage: ./0-world_wide_web <domain> <subdomain>"
fi
