#!/usr/bin/env bash
# Script to install nginx webserver on server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
