#!/usr/bin/env bash
# Install nginx
sudo apt-get update
sudo apt-get install nginx -y

# create a hello world page
echo "Hello World!" | sudo tee /var/www/html/index.html

# redirect redirect_me to the youtube page
sed -i.bak '/server_name _;/a\\n\tlocation \/redirect_me \{\n\t\treturn 301 https://www.    youtube.com/watch?v=QH2-TGUlwu4;\n\t\}' /etc/nginx/sites-available/default

# Custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '/server_name _;/a \        error_page 404 /custom_404.html;\n        location = /custom_404.html {\n                internal;\n        }' /etc/nginx/sites-available/default
sudo service nginx restart
