#!/usr/bin/env bash
# Install and configure HAproxy using roundrobin

sudo apt-get update
sudo apt-get install haproxy -y

# Loadbalancer configuration
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend myfront
        bind *:80
        default_backend myservers

backend myback
        balance roundrobin
        server web-01 54.236.33.171:80 check
        server web-02 54.90.8.140:80 check
EOT

# initialize the loadbalancer
sudo /etc/init.d/haproxy start

# Configure boot the HAProxy to boot at start
sudo update-rc.d haproxy defaults

# HAProxy reloading
sudo /etc/init.d/haproxy reload
