#!/usr/bin/env bash
# Debugging nginx web server not listening to port 80 by connecting config files

sudo service nginx status
sudo service nginx stop
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
