#!/usr/bin/env bash
# Debug in 7 lines
sudo pkill apache2
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
